version: "3"
services: 
    app:
        container_name: c_app
        working_dir: /var/www
        restart: unless-stopped
        build: 
            context: ./docker/php/
            dockerfile: Dockerfile
        image: php:latest
        volumes: 
            - ./code:/var/www
        networks: 
            - sample-network
        

    nginx:
        container_name: c_nginx
        restart: unless-stopped
        image: nginx:latest
        ports: 
            - "80:80"
        volumes: 
            - ./code:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - sample-network

networks: 
    sample-network:
        driver: bridge