apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: nginx-local
      context: docker

deploy:
  kubectl:
    manifests:
      - ./k8s/*

portForward:
  - resourceType: deployment
    resourceName: dev
    port: 80
    localPort: 80
