apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dev
  name: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dev
    spec:
      containers:
      - image: nginx-local
        name: nginx-local
        ports:
          - containerPort: 80
        resources: {}
status: {}
